### POST request with a header
POST http://localhost:8080/csrf
Content-Type: application/json

### POST request with a header
POST http://localhost:8080/csrf
Content-Type: application/x-www-form-urlencoded

_csrf = V6besSp81gmYICKq-aEsFZZjvUU3msZiVmaYBAs0vcvVrOvaYJ7m0xxFszq1FRKfwYwYJ6JWkH1UoqNPMwevMmoMhP6zntru