### GET request with a header
GET http://localhost:8080
Content-Type: application/json

### POST request with a header
POST http://localhost:8080/csrf
Content-Type: application/json

### POST request with a header
POST http://localhost:8080/csrf
Content-Type: application/x-www-form-urlencoded

_csrf = 3zf7NKUxkJVMrZI_qtRBLrzinI-A9-KeX8jlDsXF3vG84xx26weeUMRV9vNhm_Zez_l1T4vRse7llduzO_7dO_38upLY034V

### Send GET request with json body
GET http://localhost:8080/csrfToken
Content-Type: application/json