### POST request with a header
POST http://localhost:8080/csrf
Content-Type: application/json

### POST request with a header
POST http://localhost:8080/csrf
Content-Type: application/x-www-form-urlencoded

_csrf = BJwnG_GQ-wCZaev0qgTCLfcgLngMYT50Xb4vn__WkJT_v3ekNagfesXxnWW0Ud3Bzyn2SZRGAxk4VQ9ZZY5J_sblqfWe2kaW
